# Generated by Django 6.0.5 on 2026-05-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=20, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
